# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
name: Bug report
description: Create a bug report to help us improve the site
labels: ["bug"]
body:
    - type: textarea
      id: description
      attributes:
          label: Bug description
          description: Give a clear and concise description of what the bug is
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: How to reproduce
          description: A step-by-step guide on how to reproduce the bug
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behaviour
          description: Give a clear description of what you expect to happen
    - type: markdown
      attributes:
          value: |
              ## How to get your Discord id

              ### Enable Discord developer mode:
              1. In Discord go to 'User Settings' (the little cog next to your name)
              2. Under 'App Settings' go to the 'Advanced' tab
              3. Enable the 'Developer Mode' option

              ### Copy your Discord id
              1. Right click your name in the members sidebar or from a message
              2. Click 'Copy User ID'
              3. Paste the id here.
    - type: input
      id: discordid
      attributes:
          label: Discord Id
          description: Your Discord account id (if applicable), will help us find your actions in the site logs
          placeholder: ex. 255733848162304002
    - type: dropdown
      id: browsers
      attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
              - Opera
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
