# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
name: "[INTERNAL] Task"
description: Issue template for a Task item
title: "[Task]: "
labels: ["feature"]
projects: ["frontier-consolidated/1"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the task
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: The set of criteria that must be met for this issue
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: A list of dev tasks required to meet the acceptance criteria
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional information, questions, etc.
