import {
	astroidField,
	city,
	commArray,
	outpost,
	lagrangePoint,
	moon,
	planet,
	prison,
	station,
	system,
	securityPost,
	raceTrack,
	jumpPoint,
} from "../helpers";

export const Stanton = system("Stanton", [
	// star("Stanton"),
	planet("Hurston", [
		city("Lorville"),
		outpost("Reclamation & Disposal Orinth"),
		outpost("Rappell"),
		outpost("Zephyr"),
		outpost("Weeping Cove"),
		outpost("Maker's Point"),
		outpost("Picker's Field"),
		outpost("HDSF-Adlai"),
		outpost("HDSF-Ishmael"),
		outpost("HDSF-Hiram"),
		outpost("HDSF-Tompkins"),
		outpost("HDSF-Elbridge"),
		outpost("HDSF-Hobart"),
		outpost("HDSF-Millerand"),
		outpost("HDSF-Damaris"),
		outpost("HDSF-Barnabas"),
		outpost("HDSF-Breckinridge"),
		outpost("HDSF-Hendricks"),
		outpost("HDSF-Tamar"),
		outpost("HDSF-Rufus"),
		outpost("HDSF-Zacharias"),
		outpost("HDSF-Colfax"),
		outpost("HDSF-Sherman"),
		outpost("HDMS-Edmond"),
		outpost("HDMS-Stanhope"),
		outpost("HDMS-Thedus"),
		outpost("HDMS-Oparei"),
		outpost("HDMS-Pinewood"),
		outpost("HDES-Calthrope (NA)"),
		station("Everus Harbor"),
		commArray("Comm Array ST1-61"),
		moon("Arial", [
			outpost("HDMS-Bezdek"),
			outpost("HDMS-Lathan"),
			commArray("Comm Array ST1-13"),
		]),
		moon("Aberdeen", [
			outpost("HDMS-Anderson"),
			outpost("HDMS-Norgaard"),
			outpost("HDES-Dobbs (NA)"),
			outpost("Barton Flats Aid Shelter"),
			prison("Klescher Rehabilitation Facility"),
			commArray("Comm Array ST1-92"),
		]),
		moon("Magda", [
			outpost("HDMS-Hahn"),
			outpost("HDMS-Perlman"),
			commArray("Comm Array ST1-48"),
		]),
		moon("Ita", [
			outpost("HDMS-Ryder"),
			outpost("HDMS-Woodruff"),
			commArray("Comm Array ST1-02"),
		]),
	]),
	planet("Crusader", [
		city("Orison"),
		outpost("Prospect Point"),
		outpost("Empyrean Park"),
		outpost("Cloudrest Retreat"),
		station("Seraphim Station"),
		commArray("Comm Array ST2-55"),
		moon("Cellin", [
			outpost("Tram & Myers Mining"),
			outpost("PRIVATE PROPERTY"),
			outpost("Gallete Family Farms"),
			outpost("Terra Mills HydroFarm"),
			outpost("NT-999-XV"),
			outpost("Hickes Research Outpost"),
			outpost("Mogote Aid Shelter"),
			outpost("Ashburn Channel Aid Shelter"),
			outpost("Flanagan's Ravine Aid Shelter"),
			outpost("Julep Ravine Aid Shelter"),
			securityPost("Security Post Lespin"),
			securityPost("Security Post Dipur"),
			securityPost("Security Post Criska"),
			securityPost("Security Post Kareah", true),
			commArray("Comm Array ST2-28"),
		]),
		moon("Daymar", [
			outpost("Brio's Breaker Yard"),
			outpost("The Garden"),
			outpost("Nuen Waste Management"),
			outpost("Kudre Ore Mine (Closed)"),
			outpost("TPF"),
			outpost("Kudre Ore"),
			outpost("Bountiful Harvest Hydroponics"),
			outpost("Tamdon Plains Aid Shelter"),
			outpost("Dunlow Ridge Aid Shelter"),
			outpost("Wolf Point Aid Shelter"),
			outpost("Eager Flats Aid Shelter"),
			outpost("Shubin Mining Facility SCD-1"),
			outpost("ArcCorp Mining Area 141"),
			securityPost("Security Post Thaquray"),
			securityPost("Security Post Prashad"),
			securityPost("Security Post Moluto"),
			station("Covalex Shipping Hub Gundo"),
			commArray("Comm Array ST2-47"),
		]),
		moon("Yela", [
			outpost("NT-999-XX"),
			outpost("NT-999-XXII"),
			outpost("Afterlife"),
			outpost("Utopia"),
			outpost("Connor's"),
			outpost("Deakins Research Outpost"),
			outpost("Talarine Divide Aid Shelter"),
			outpost("Nakamura Valley Aid Shelter"),
			outpost("Kosso Basin Aid Shelter"),
			outpost("Aston Ridge Aid Shelter"),
			outpost("Benson Mining Outpost"),
			outpost("ArcCorp Mining Area 157"),
			securityPost("Security Post Wan"),
			securityPost("Security Post Opal"),
			raceTrack("Miner's Lament", true),
			station("Grim HEX"),
			commArray("Comm Array ST2-76"),
		]),
	]),
	planet("ArcCorp", [
		city("Area18"),
		outpost("The Sky Scraper"),
		outpost("Area04"),
		outpost("Area06"),
		outpost("Area11"),
		outpost("Area17"),
		outpost("Area20"),
		station("Baijini Point"),
		commArray("Comm Array ST3-90"),
		moon("Lyria", [
			outpost('"The Pit"'),
			outpost("<= UNINITIALIZED =>"),
			outpost("Elsewhere"),
			outpost('"Wheeler\'s"'),
			outpost("The Orphanage"),
			outpost("Humboldt Mines"),
			outpost("Loveridge Mineral Reserve"),
			outpost("Launch Pad"),
			outpost("Buckets"),
			outpost("Shubin Mining Facility SAL-2"),
			outpost("Shubin Mining Facility SAL-5"),
			outpost("Shubin Processing Facility SPAL-9"),
			outpost("Shubin Processing Facility SPAL-7"),
			outpost("Shubin Processing Facility SPAL-16"),
			outpost("Shubin Processing Facility SPAL-21"),
			outpost("Shubin Processing Facility SPAL-12"),
			outpost("Shubin Processing Facility SPAL-3"),
			outpost("Teddy's Playhouse"),
			commArray("Comm Array ST3-18"),
		]),
		moon("Wala", [
			outpost("Good Times Temple"),
			outpost("Lost and Found"),
			outpost("Shady Glen Farms"),
			outpost("Paradise Cove"),
			outpost("Samson & Son's Salvage Center"),
			outpost("ArcCorp Processing Center 115"),
			outpost("ArcCorp Processing Center 123"),
			outpost("ArcCorp Mining Area 045"),
			outpost("ArcCorp Mining Area 048"),
			outpost("ArcCorp Mining Area 056"),
			outpost("ArcCorp Mining Area 061"),
			commArray("Comm Array ST3-35"),
		]),
	]),
	planet("microTech", [
		city("New Babbage"),
		outpost("The Necropolis"),
		outpost("Raven's Roost"),
		outpost("Ghost Hollow"),
		outpost("Harper's Point"),
		outpost("Dunboro"),
		outpost("Astor's Clearing"),
		outpost("Outpost 54"),
		outpost("Rayari Deltana Research Outpost"),
		outpost("Shubin Mining Facility SMO-22"),
		outpost("Shubin Mining Facility SMO-10"),
		outpost("Shubin Mining Facility SMO-13"),
		outpost("Shubin Mining Facility SMO-18"),
		outpost("Point Wain Emergency Shelter"),
		outpost("Clear View Emergency Shelter"),
		outpost("Nuiqsut Emergency Shelter"),
		outpost("Calhoun Pass Emergency Shelter"),
		outpost("MT OpCenter TLI-4"),
		outpost("MT DataCenter TMG-XEV-2"),
		outpost("MT DataCenter 5WQ-R2V-C"),
		outpost("MT DataCenter E2Q-NSG-Y"),
		outpost("MT DataCenter 2UB-RB9-5"),
		outpost("MT DataCenter 4HJ-LVE-A"),
		outpost("MT DataCenter KH3-AAE-L"),
		outpost("MT DataCenter QVX-J88-J"),
		outpost("MT DataCenter D79-ECG-R"),
		outpost("MT DataCenter L8P-JUC-8 (Offline)"),
		outpost("MT DataCenter 8FK-Q2X-K"),
		station("Port Tressler"),
		commArray("Comm Array ST4-22"),
		moon("Calliope", [
			outpost("Rayar Kaltag Research Outpost"),
			outpost("Rayari Anvik Research Outpost"),
			outpost("Shubin Processing Facility SPMC-14"),
			outpost("Shubin Processing Facility SPMC-3"),
			outpost("Shubin Processing Facility SPMC-5"),
			outpost("Shubin Processing Facility SPMC-11"),
			outpost("Shubin Processing Facility SPMC-10"),
			outpost("Shubin Mining Facility SMCa-6"),
			outpost("Shubin Mining Facility SMCa-8"),
			commArray("Comm Array ST4-31"),
		]),
		moon("Clio", [
			outpost("Rayari McGrath Research Outpost"),
			outpost("Rayari Cantwell Research Outpost"),
			commArray("Comm Array ST4-59"),
		]),
		moon("Euterpe", [
			outpost("The Icebreaker"),
			outpost("Bud's Growery"),
			outpost("Devlin Scrap & Salvage"),
			commArray("Comm Array ST4-64"),
		]),
	]),
	lagrangePoint("HUR L1", [astroidField("HUR L1-A"), station("HUR-L1 Green Glade Station")]),
	lagrangePoint("HUR L2", [astroidField("HUR L2-A"), station("HUR-L2 Faithful Dream Station")]),
	lagrangePoint("HUR L3", [
		astroidField("HUR L3-A"),
		station("HUR-L3 Thundering Express Station"),
	]),
	lagrangePoint("HUR L4", [astroidField("HUR L4-A"), station("HUR-L4 Melodic Fields Station")]),
	lagrangePoint("HUR L5", [astroidField("HUR L5-A"), station("HUR-L5 High Course Station")]),
	lagrangePoint("CRU L1", [astroidField("CRU L1-A"), station("CRU-L1 Ambitious Dream Station")]),
	lagrangePoint("CRU L2", [
		astroidField("CRU L2-A"),
		astroidField("CRU L2-B"),
		astroidField("CRU L2-C"),
	]),
	lagrangePoint("CRU L3", [astroidField("CRU L3-A")]),
	lagrangePoint("CRU L4", [astroidField("CRU L4-A"), station("CRU-L4 Shallow Fields Station")]),
	lagrangePoint("CRU L5", [astroidField("CRU L5-A"), station("CRU-L5 Beautiful Glen Station")]),
	lagrangePoint("ARC L1", [astroidField("ARC L1-A"), station("ARC-L1 Wide Forest Station")]),
	lagrangePoint("ARC L2", [astroidField("ARC L2-A"), station("ARC-L2 Lively Pathway Station")]),
	lagrangePoint("ARC L3", [astroidField("ARC L3-A"), station("ARC-L3 Modern Express Station")]),
	lagrangePoint("ARC L4", [astroidField("ARC L4-A"), station("ARC-L4 Faint Glen Station")]),
	lagrangePoint("ARC L5", [astroidField("ARC L5-A"), station("ARC-L5 Yellow Core Station")]),
	lagrangePoint("MIC L1", [astroidField("MIC L1-B"), station("INS Jericho")]),
	lagrangePoint("MIC L2", [
		astroidField("MIC L2-A"),
		astroidField("MIC L2-B"),
		astroidField("MIC L2-C"),
		station("MIC-L2 Long Forest Station"),
	]),
	lagrangePoint("MIC L3", [astroidField("MIC L3-A"), station("MIC-L3 Endless Odyssey Station")]),
	lagrangePoint("MIC L4", [astroidField("MIC L4-A"), station("MIC-L4 Red Crossroads Station")]),
	lagrangePoint("MIC L5", [astroidField("MIC L5-A"), station("MIC-L5 Modern Icarus Station")]),
	jumpPoint("Stanton - Pyro Jump Point", [station("Pyro Gateway")]),
	jumpPoint("Stanton - Terra Jump Point", [station("Terra Gateway")]),
	jumpPoint("Stanton - Magnus Jump Point", [station("Magnus Gateway")]),
]);
