name: Development

on:
  push:
    branches:
      - dev
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/CODEOWNERS
      - .github/ISSUE_TEMPLATE/**

jobs:
  call-deploy:
    name: Deploy to dev
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: frontierconsolidated.com
      hostname: dev.frontierconsolidated.com
      service: frcn-dev.service
    secrets: inherit
