name: Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/CODEOWNERS
      - .github/ISSUE_TEMPLATE/**

jobs:
  call-deploy:
    name: Deploy to prod
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: frontierconsolidated.com
      hostname: frontierconsolidated.com
      service: frcn.service
    secrets: inherit
