name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6

      - name: Cache Trivy database
        uses: actions/cache@v5
        with:
          path: ~/.cache/trivy/
          key: trivy-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
